package com.company.enums;

public enum Status {

    GIVE_CONTACT,
    GIVE_LANGUAGE,
    GIVE_FULL_NAME,
    USER_SHOW_CATEGORY,
    USER_SETTING_MENU,
    SET_LANGUAGE,
    SET_NEW_FULLNAME,
    SET_NEW_CONTACT,
    USER_SHOW_PRODUCT,
    USER_SHOW_LIKED,

    USER_GIVE_REKLAMA,
    USER_SEND_PRODUCT_PHOTO,
    USER_SEND_PRODUCT_CONTACT,
    USER_SEND_PRODUCT_LOCATION,
    USER_SEND_PRODUCT_INFO,
    USER_SHOW_OWN_PRODUCT,
    MENU,
    SETTING,
    REFRESH,

    ADMIN_MENU,
    ADMIN_SEND_CUSTOMER_RESPONSE,
    ADMIN_ADD_OR_REVOKE_ADMIN,
    PREMIUM_REKLAMA,
    CATEGORY_CRUD,
    ADMIN_CUSTOMER_CRUD,
    BLOCKED_USER,
    ADMIN_WRITE_RESPONSE,
    WAIT_RESPONSE,
    ADMIN_CREATE_CATEGORY,
    ADMIN_SHOW_CATEGORY,
    ADMIN_UPDATE_CATEGORY,
    ADMIN_DELETED_CATEGORY,

}
